---
title: "Nadal vs Djokovic" 
author: "Enrico Peressin"
date: "Settembre 2023"
output:
  ioslides_presentation:
    widescreen: true
    transition: faster
    css: style.css
  slidy_presentation: default
  beamer_presentation: default
subtitle: Roland Garros 2022
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 5, fig.height = 5) # hides code chunks by default. Use echo = TRUE to show. 
```

```{r libraries, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(png)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(magick)
library(grid)
library(gridtext)
```

```{r data, cache=FALSE}
# files ----
data <- read.csv("2022RG_final.csv") 
court_test = read.csv("courtdimensions.csv") # test data frame to calibrate the court image
half_court = image_read("half-clay-court.png")
half_court_180 = image_flip(half_court)
half_court_long = image_read("half-clay-court-long.png")
half_court_long_180 = image_flip(half_court_long)
full_court = image_read("full-clay-court.png")
full_court_90 = image_rotate(full_court, 90)
full_court_90_BW = image_rotate(image_read("full-clay-court-b.png"), 90)

# DATA ----

# Serve 
serves_djoko <- data %>%
  filter(Player == "Player1" & Shot_Type %in% c("1st Serve", "2nd Serve")) %>%
  filter(Y2 > -6.4 & Y2 < 6.4 & (Y2 < -1 | Y2 > 1) & (X2 < 4.1 | X2 < -4.1)) %>% # filter out faults
  select(Player, Shot_Type, X2, Y2) %>%
  mutate(X2 = ifelse(Y2 < 0, -X2, X2)) # flip X axis value for bottom half court values

serves_djoko_all <- data %>% 
  filter(Player == "Player1" & Shot_Type %in% c("1st Serve", "2nd Serve"))

serves_djoko_count <- table(serves_djoko_all$Shot_Type)
first_serve_djoko_percentage <- ((serves_djoko_count["1st Serve"] - serves_djoko_count["2nd Serve"]) / serves_djoko_count["1st Serve"]) * 100

serves_nadal <- data %>%
  filter(Player == "Player2" & Shot_Type %in% c("1st Serve", "2nd Serve")) %>%
  filter(Y2 > -6.4 & Y2 < 6.4 & (Y2 < -1 | Y2 > 1) & (X2 < 4.1 | X2 > -4.1)) %>%
  select(Player, Shot_Side, Shot_Type, X2, Y2, Serve_Speed) %>%
  mutate(X2 = ifelse(Y2 < 0, -X2, X2))

serves_nadal_all <- data %>% 
  filter(Player == "Player2" & Shot_Type %in% c("1st Serve", "2nd Serve"))

serves_nadal_count <- table(serves_nadal_all$Shot_Type)
first_serve_nadal_percentage <- ((serves_nadal_count["1st Serve"] - serves_nadal_count["2nd Serve"]) / serves_nadal_count["1st Serve"]) * 100

# Serve speed ----

serve_speed_nadal <- data %>% 
  filter(Player == "Player2" & Shot_Type %in% c("1st Serve", "2nd Serve")) %>% 
  select(Serve_Speed, Set, Shot_Type, Point_Winner, Stroke_Number, Outcome) %>% 
  mutate(isAce = ifelse((Point_Winner == 2) & Stroke_Number == 1 & Outcome == "Winner", TRUE, FALSE)) %>% 
  filter(Serve_Speed != "Unknown")

mean_nadal_serve_speed <- serve_speed_nadal %>% # new data frame with mean serve speed for each combination of Set and Shot_Type
  group_by(Shot_Type, Set) %>% 
  summarise(mean_serve_speed = round(mean(as.numeric(Serve_Speed))),
            .groups = "drop") # Remove the grouping

serve_speed_djoko <- data %>% 
  filter(Player == "Player1" & Shot_Type %in% c("1st Serve", "2nd Serve")) %>% 
  select(Serve_Speed, Set, Shot_Type, Point_Winner, Stroke_Number, Outcome) %>% 
  mutate(isAce = ifelse((Point_Winner == 1) & Stroke_Number == 1 & Outcome == "Winner", TRUE, FALSE)) %>% 
  filter(Serve_Speed != "Unknown")

mean_djoko_serve_speed <- serve_speed_djoko %>% 
  group_by(Shot_Type, Set) %>% 
  summarise(mean_serve_speed = round(mean(as.numeric(Serve_Speed))),
            .groups = "drop")

control_row <- data.frame(
  X = c(-5.48, -4.11, 0, 4.11, 5.48, 0),
  Y = c(-11.88, -11.88, -11.88, -11.88, -11.88, 0),
  Player = c("Player2", "Player2", "Player2", "Player2", "Player2", "Player2"),
  Outcome = c("1", "2", "3", "4", "5", "6"),
  Shot_Type = c("1", "2", "3", "4", "5", "6"),
  Shot_Side = c("1", "2", "3", "4", "5", "6")
)

# Strike point----

divisions = c(-7.5, -4.5, -1.5, 1.5, 4.5, 7.5)
divisions2 = c(-7.5, -4.5, -1.5, 1.5, 4.5)

strikepoint_nadal <- data %>% 
  filter(Player == "Player2" & Stroke_Number > 2 & abs(Y)>7.5 & !(Shot_Type %in% c("1st Serve", "2nd Serve"))) %>%
  select(Player, X, Y, Outcome, Shot_Type, Shot_Side) %>% 
  mutate(X = ifelse(Y < 0, X, -X)) 

strikepoint_nadal_avg <- strikepoint_nadal %>% 
  mutate(section = cut(X, breaks = divisions)) %>% 
  count(section) %>% 
  mutate(percentage = n / sum(n)*100)

strikepoint_djokovic <- data %>% 
  filter(Player == "Player1" & Stroke_Number > 2 & abs(Y)>7.5 & !(Shot_Type %in% c("1st Serve", "2nd Serve"))) %>%
  select(Player, X, Y, Outcome, Shot_Type, Shot_Side) %>% 
  mutate(X = ifelse(Y < 0, X, -X)) 

strikepoint_djokovic_avg <- strikepoint_djokovic %>% 
  mutate(section = cut(X, breaks = divisions)) %>% 
  count(section) %>% 
  mutate(percentage = n / sum(n)*100)

strikepoint_djokovic_avg$Color_Code <- ifelse(
  strikepoint_djokovic_avg$percentage >= 35, "#000000",  # Red color for values >= 80%
  ifelse(
    strikepoint_djokovic_avg$percentage >= 20, "#282828",  # Orange color for values >= 60%
    "#505050"  # Default color for other values
  )
)

strikepoint_nadal_avg$Color_Code <- ifelse(
  strikepoint_nadal_avg$percentage >= 35, "#000000",  # Red color for values >= 80%
  ifelse(
    strikepoint_nadal_avg$percentage >= 20, "#282828",  # Orange color for values >= 60%
    "#505050"  # Default color for other values
  )
)
# testbind <- rbind(strikepoint_djokovic, control_row)

# Backhand ---- 
djoko_backhand <- data %>% 
  filter(Player == "Player1" & Shot_Side == "BH" & Stroke_Number>2  & !(Shot_Type %in% c(
                                                                                         "Volley",
                                                                                         "Swing-volley",
                                                                                         "Drop-Shot", 
                                                                                         "Drop-volley", 
                                                                                         "Overhead",
                                                                                         "Lob Volley")) 
         & X<0) %>% 
  select(X, Y, X2, Y2, Outcome, Shot_Type, Point_Winner) %>% 
  mutate(X = ifelse(Y > 0, -X, X),
         X2 = ifelse(Y2 > 0, -X2, X2))
dbh_count <- table(djoko_backhand$Outcome)

nadal_backhand <- data %>% 
  filter(Player == "Player2" & Shot_Side == "BH" & Stroke_Number>2  & !(Shot_Type %in% c(
                                                                                         "Volley",
                                                                                         "Swing-volley",
                                                                                         "Drop-Shot", 
                                                                                         "Drop-volley", 
                                                                                         "Overhead",
                                                                                         "Lob Volley")) 
         & X<0) %>% 
  select(X, Y, X2, Y2, Outcome, Shot_Type, Point_Winner) %>% 
  mutate(X = ifelse(Y > 0, -X, X),
         X2 = ifelse(Y2 > 0, -X2, X2))
nbh_count <- table(nadal_backhand$Outcome)
# Forehand----

djoko_forehand <- data %>% 
  filter(Player == "Player1" & Shot_Side == "FH" & Stroke_Number>2  & !(Shot_Type %in% c(
                                                                                         "Volley",
                                                                                         "Swing-volley",
                                                                                         "Drop-Shot", 
                                                                                         "Drop-volley", 
                                                                                         "Overhead",
                                                                                         "Lob Volley"))) %>% 
  select(X, Y, X2, Y2, Outcome, Shot_Type, Point_Winner, Shot_Side) %>% 
  mutate(X = ifelse(Y > 0, -X, X),
         X2 = ifelse(Y2 > 0, -X2, X2)) %>% 
  filter(X>0)
dfh_count <- table(djoko_forehand$Outcome)

nadal_forehand <- data %>% 
  filter(Player == "Player2" & Shot_Side == "FH" & Stroke_Number>2  & !(Shot_Type %in% c(
                                                                                         "Volley",
                                                                                         "Swing-volley",
                                                                                         "Drop-Shot", 
                                                                                         "Drop-volley", 
                                                                                         "Overhead",
                                                                                         "Lob Volley"))) %>% 
  select(X, Y, X2, Y2, Outcome, Shot_Type, Point_Winner, Shot_Side) %>% 
  mutate(X = ifelse(Y > 0, -X, X),
         X2 = ifelse(Y2 > 0, -X2, X2)) %>% 
  filter(X>0)

nadal_forehand_insidein <- nadal_forehand %>% 
  filter(X2>2)

nfh_count <- table(nadal_forehand$Outcome)
nfhii_count <- table(nadal_forehand_insidein$Outcome)

# Slice

djoko_dropshot <- data %>% 
  filter(Player == "Player1" & Shot_Type == "Drop-Shot") %>% 
  select(X, Y, X2, Y2, Outcome, Point_Winner) %>% 
  mutate(X = ifelse(Y > 0, -X, X),
         X2 = ifelse(Y2 > 0, -X2, X2))
dds_count <- table(djoko_dropshot$Outcome)

djoko_slice <- data %>% 
  filter(Player == "Player1" & Shot_Type == "Slice") %>% 
  select(X, Y, X2, Y2, Outcome, Point_Winner, Point) %>% 
  mutate(X = ifelse(Y > 0, -X, X),
         X2 = ifelse(Y2 > 0, -X2, X2))
ds_count <- table(djoko_slice$Outcome)
```


## L'incontro

[---]

## Serve bounce position
```{r court calibration, eval=FALSE}
## Court Calibration ## ----
test_Hcourt_plot = ggplot(court_test, aes(x=X2, y=Y2))+
  geom_point() + 
  theme_void()+
  theme(aspect.ratio = 1) + 
  xlim(c(-6, 6)) + 
  ylim(c(0, 12)) 

ggdraw()+
  draw_image(half_court, scale = 1)+
  draw_plot(test_Hcourt_plot, x=0, y=-0.06, scale=0.85)
```
<span class = "outlined">**First**</span> and <span style="color:#030303;"> **second** </span> serve placement density map

<div class = "row">
<div class = "column">
```{r Nadal Serve position, eval=TRUE, cache=TRUE}
nadal_serve_pos_plot <- ggplot(serves_nadal, aes(x = X2, y = abs(Y2))) +
  stat_density_2d(aes(fill = after_stat(density)),
    geom = "raster",
    contour = FALSE,
    h = c(1, 2) # control x and y bandwidths of the estimate.
  ) +
  scale_fill_gradientn(colors = c(
    "transparent", # scale that is transparent on the smallest end of the range
    viridis::viridis_pal(
      alpha = 0.5,
      option = "turbo"
    )(10) # number of colors in the scale
  ), guide = "none") +
  geom_point(
    aes(colour = factor(Shot_Type)) # maps colour aesthetic to categorical variable (Shot_Type)
  ) +
  scale_colour_manual(values = c("1st Serve" = "#FFFFFFAA", "2nd Serve" = "#000000AA")
                      )+
  theme_void() +
  theme(aspect.ratio = 1, legend.position = "none") +
  xlim(c(-6, 6)) +
  ylim(c(0, 12)) +
  ggtitle("Nadal") +
  theme(plot.title = element_text(hjust = .5,
                                  vjust = -7,
                                  face = "bold",
                                  family = "mono",
                                  size = 16, 
                                  color = "#37230e")
        )
first_serve_nadal_percentage_grob = grobTree(textGrob(
  paste("First serve %: ", paste0(round(first_serve_nadal_percentage, 1), "%")),
  x = .5, y = .8,gp=gpar(fontfamily="mono", fontsize = 15)))

ggdraw()+
  draw_image(half_court, scale = 1.25)+
  draw_plot(nadal_serve_pos_plot, x=0, y=-0.04, scale=1.17)+
  annotation_custom(first_serve_nadal_percentage_grob)
```
</div>
<div class = "column">
```{r Djokovic serve position, eval=TRUE, cache=TRUE}
djoko_serve_pos_plot <- ggplot(serves_djoko, aes(x = X2, y = abs(Y2))) +
  stat_density_2d(aes(fill = after_stat(density)),
    geom = "raster",
    contour = FALSE,
    h = c(1, 2)
  ) +
  scale_fill_gradientn(colors = c(
    "transparent",
    viridis::viridis_pal(
      alpha = 0.5,
      option = "turbo"
    )(10)
  )) +
  geom_point(
    aes(colour = factor(Shot_Type))
  ) +
  scale_colour_manual(values = c("1st Serve" = "#FFFFFFAA", "2nd Serve" = "#000000AA"))+
  theme_void() +
  theme(aspect.ratio = 1, legend.position = "none") +
  xlim(c(-6, 6)) +
  ylim(c(0, 12)) +
  ggtitle("Djokovic") +
  theme(plot.title = element_text(hjust = .5, 
                                  vjust = -7,
                                  face = "bold",
                                  family = "mono",
                                  size = 16,
                                  color = "#37230e")
        )
first_serve_djoko_percentage_grob = grobTree(textGrob(
  paste("First serve %: ", paste0(round(first_serve_djoko_percentage, 1), "%")),
  x = .5, y = .8, gp=gpar(fontfamily="mono", fontsize = 15)))

ggdraw()+
  draw_image(half_court, scale = 1.25)+
  draw_plot(djoko_serve_pos_plot, x=0, y=-0.04, scale=1.15)+
  annotation_custom(first_serve_djoko_percentage_grob)

```
</div>
</div>

## <span style="color:#4E80DB;">First</span> and <span style="color:#DAB157;">second</span> serve speeds
```{r Nadal serve speed, eval=TRUE, cache=TRUE}
pp1 = ggdraw()+
  draw_plot(
    nadal_serve_speed_plot <- ggplot(serve_speed_nadal, 
                                 aes(x = as.numeric(Serve_Speed),
                                     y = reorder(Set, desc(Set)))
                                 )+
    geom_point(
      aes(
      colour = ifelse(isAce, "red", ifelse(Shot_Type == "1st Serve", "blue", "yellow")),  # not actual colors, but it works
      shape = factor(isAce),
      size = factor(isAce)), 
    position = position_jitter(height = 0.14), 
    na.rm = TRUE # missing values are removed without warning
  ) +
  geom_text(
    data = mean_nadal_serve_speed, 
    aes(label= mean_serve_speed, x = mean_serve_speed), 
    vjust = 3.5,
    size = 3.5
  )+
  stat_summary(
    na.rm = TRUE,
    fun = mean,
    aes(group = interaction(Set, Shot_Type)),  # Group by Set and Shot_Type
    shape = "|",
    colour = "#000B1CB5",
    size = 2.14,
    show.legend = TRUE
  )+
  labs(
    title = "Nadal", 
    x = NULL,
    # y = "Set",
    y = " ",
    cex.lab = 8
  )+
  scale_color_manual(values= c("#4E80DB", "#da6c5bAA", "#DAB157"))+
  scale_size_manual(values = c("FALSE" = 3, "TRUE" = 4.5))+
  scale_shape_manual(values = c("FALSE" = 20, "TRUE" = 18))+
  theme_minimal()+
  # scale_x_continuous(breaks = c(125, 150, 175, 200), labels = c(125, 150, 175, 200))+
  guides(color = FALSE, shape = FALSE, size = FALSE)+
    xlim(125, 201)+
  theme(
    plot.title = element_text(hjust = 0.5,
                              face = "bold",
                              family = "mono",
                              size = 16),
    axis.text = element_text(size=13),
    axis.title = element_text(size = 10) 
  )
)
```

```{r Djokovic serve speed, eval=TRUE, cache=TRUE}
pp2 = ggdraw()+
  draw_plot(
djoko_serve_speed_plot <- ggplot(serve_speed_djoko,
                                 aes(x = as.numeric(Serve_Speed),
                                     y = reorder(Set, desc(Set))))+
  geom_point(
    # size = 3, 
    aes(
      # colour = factor(isAce), 
      colour = ifelse(isAce, "red", ifelse(Shot_Type == "1st Serve", "blue", "yellow")),  
      shape = factor(isAce),
      size = factor(isAce)), 
    position = position_jitter(height = 0.14), 
    na.rm = TRUE 
  ) + 
  geom_text(
    data = mean_djoko_serve_speed, 
    aes(label= mean_serve_speed, x = mean_serve_speed), 
    vjust = 3.5,
    size = 3.5
  )+
  stat_summary(
    na.rm = TRUE,
    fun = mean,
    aes(group = interaction(Set, Shot_Type)),  # Group by Set and Shot_Type
    shape = "|",
    colour = "#000B1CB5",
    size = 2.14,
    show.legend = TRUE
  )+
  labs(
    title = "Djokovic",
    # x = "Serve speed (Km/h)",
    x = NULL,
    y = NULL
  )+
  scale_color_manual(values= c("#4E80DB", "#da6c5bCC", "#DAB157"))+
  scale_shape_manual(values = c("FALSE" = 20, "TRUE" = 18))+
  scale_size_manual(values = c("FALSE" = 3, "TRUE" = 4.5))+
  theme_minimal()+
  # scale_x_continuous(breaks = c(125, 150, 175, 200), labels = c(125, 150, 175, 200))+
  guides(colour = FALSE, shape = FALSE, size = FALSE)+
      xlim(125, 201)+
  theme(
    plot.title = element_text(hjust = 0.5,
                              face = "bold",
                              family = "mono",
                              size = 16),
    axis.text = element_text(size=13)
  )
)
```

```{r plot grid serve speed, fig.height=5.5, fig.width=10}
text_label = "Serve speed (Km/h)"
dot_label = "<span style = 'color: #da6c5bcc; font-size: 30px'> ◆ </span> = Ace 
             <span style = 'color: #000B1CB5; font-size: 35px'> | </span> = avg"  

grid.arrange(pp1, pp2, ncol = 2, bottom = text_grob(
  label = text_label,
  x =  0.5, hjust = 0.5, color = "#222222", size= 16),
  left = text_grob("Set", size = 16, rot =90, color = "#222222"), 
  right = richtext_grob(dot_label, rot = -90)
)
```


## Strike point density map

<div class = "row">
<div class = "column">
```{r strikepoint Nadal, eval=TRUE, warning=FALSE}
strikeplot = ggplot(strikepoint_nadal, aes(x = X, y = -abs(Y)))+
  geom_point(
    aes(colour = Shot_Side)
  )+ 
  theme_void()+
  theme(
    aspect.ratio = 1,
    legend.position = "bottom",
    legend.box = "horizontal"
  )+
  labs(
    colour = "", 
    x = 2
  )+
  xlim(c(-8, 8)) +
  ylim(c(-16, 0)) +
  geom_vline(
    xintercept = divisions, linetype = 5,  color = "#111111AA"
  )+
 geom_text(
    data = strikepoint_nadal_avg,
    aes(x = divisions2 + 1.5, y = -5, label=paste0(round(percentage, 1), "%")), size = 5.5, colour = strikepoint_nadal_avg$Color_Code
  )+
  scale_color_identity()+
  scale_color_manual(values = c("FH" = "#1D4285AA", "BH" = "#942818AA"), labels = c("Backhand", "Forehand"))+
  ggtitle("Nadal") +
  theme(plot.title = element_text(hjust = .5,
                                  vjust = -20,
                                  face = "bold",
                                  family = "mono",
                                  size = 16,
                                  color = "#222222"))

ggdraw()+
  draw_image(half_court_long_180, scale = 1)+
  draw_plot(strikeplot, x = 0, y = .065, scale = .97)
```
</div>
<div class = "column">
```{r strikepoint Djokovic, eval=TRUE, warning=FALSE}
strikeplot = ggplot(strikepoint_djokovic, aes(x = X, y = -abs(Y)))+
  geom_point(
    aes(colour = Shot_Side)
  )+ 
  theme_void()+
  theme(
    aspect.ratio = 1,
    legend.position = "bottom",
    legend.box = "horizontal"
  )+
  labs(
    colour = "", 
    x = 2
  )+
  xlim(c(-8, 8)) +
  ylim(c(-16, 0)) +
  geom_vline(
    xintercept = divisions, linetype = 5,  color = "#111111AA"
  )+
  geom_text(
    data = strikepoint_djokovic_avg,
    aes(x = divisions2 + 1.5, y = -5, label=paste0(round(percentage, 1), "%")), size = 5.5, colour = strikepoint_djokovic_avg$Color_Code
  )+
  scale_color_identity()+
  scale_color_manual(values = c("FH" = "#1D4285AA", "BH" = "#942818AA"), labels = c("Backhand", "Forehand"))+
  ggtitle("Djokovic") +
  theme(plot.title = element_text(hjust = .5,
                                  vjust = -20,
                                  face = "bold",
                                  family = "mono",
                                  size = 16,
                                  color = "#222222"))

ggdraw()+
  draw_image(half_court_long_180, scale = 1)+
  # draw_plot(strikeplot, x = 0, y = .13, scale = 1.25)
  draw_plot(strikeplot, x = 0, y = .065, scale = .97)
```
</div>
</div>

## Djokovic backhand groundstrokes

```{r Djokovic Bakhand, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 djoko_backhand_plot <- ggplot(djoko_backhand)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
      values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Forced-Error" = "#FF8C0088",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(dbh_count), "  (", dbh_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
   scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Forced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .17),
      legend.text = element_text(color = "#ffffff")
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(djoko_backhand_plot, x = 0, y = 0, scale = 1.15)
```


## Nadal backhand groundstrokes

```{r Nadal Bakhand, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 nadal_backhand_plot <- ggplot(nadal_backhand)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
     values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Forced-Error" = "#FF8C0088",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(nbh_count), "  (", nbh_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
  scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Forced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .85), 
      legend.text = element_text(color = "#ffffff"),
      legend.background = element_rect(
        fill = "#242424EE", colour = "#242424EE"
      )
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(nadal_backhand_plot, x = 0, y = 0, scale = 1.15)
```

## Djokovic forehand groundstrokes

```{r Djokovic Forehand, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 djoko_forehand_plot <- ggplot(djoko_forehand)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
      values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Forced-Error" = "#FF8C0088",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(dfh_count), "  (", dfh_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
   scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Forced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .85),
      legend.text = element_text(color = "#ffffff"),
      legend.background = element_rect(
        fill = "#242424EE", colour = "#242424EE"
      )
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(djoko_forehand_plot, x = 0, y = 0, scale = 1.15)
```

## Nadal forehand groundstrokes

```{r Nadal Forehand, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 nadal_forehand_plot <- ggplot(nadal_forehand)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
     values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Forced-Error" = "#FF8C0088",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(nfh_count), "  (", nfh_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
  scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Forced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .85), 
      legend.text = element_text(color = "#ffffff"),
      legend.background = element_rect(
        fill = "#242424EE", colour = "#242424EE"
      )
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(nadal_forehand_plot, x = 0, y = 0, scale = 1.15)
```

## Nadal 

```{r Nadal Forehand inside-in, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 nadal_forehand_plot <- ggplot(nadal_forehand_insidein)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
     values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(nfhii_count), "  (", nfhii_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
  scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .9), 
      legend.text = element_text(color = "#ffffff"),
      legend.background = element_rect(
        fill = "#242424EE", colour = "#242424EE"
      )
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(nadal_forehand_plot, x = 0, y = 0, scale = 1.15)
```

## Djokovic is out of touch

```{r Djokovic DropShot, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 djoko_forehand_plot <- ggplot(djoko_dropshot)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
      values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Forced-Error" = "#FF8C0088",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(dds_count), "  (", dds_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
   scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Forced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .9),
      legend.text = element_text(color = "#ffffff"),
      legend.background = element_rect(
        fill = "#242424EE", colour = "#242424EE"
      )
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(djoko_forehand_plot, x = 0, y = 0, scale = 1.15)
```

## Djokovic is out of touch 

```{r Djokovic Slice, eval=TRUE, fig.height=5, fig.width=10, fig.align='left'}

 djoko_forehand_plot <- ggplot(djoko_slice_v2)+
    geom_segment(aes(x = -abs(Y),
                     y = X, 
                     xend = abs(Y2), 
                     yend = X2, 
                     color = Outcome), 
                 size = 1.1,
                 arrow = arrow(length = unit(0.4, "cm"), ends = "last"))+
    scale_color_manual(
      values = c(
        "In-Play" = "#AAAAAA33",
        "Unforced-Error" = "#DB2F18A0",
        "Forced-Error" = "#FF8C0088",
        "Winner" = "#239CCCAA"),
      labels = paste0(names(ds_count), "  (", ds_count, ")"),
      guide = guide_legend(
        title = "",
        reverse = TRUE,
        direction = "vertical"
      )
    )+
   scale_size_manual(
     values = c(
       "In-Play" = 0.8,
       "Unforced-Error" = 1.1,
       "Forced-Error" = 1.1,
       "Winner" = 1.2
     ),
     guide = "none"
   )+
   # geom_point(
   #   data = court_test, 
   #   aes(x = Y, y = X)
   # )+
    xlim(-16, 16)+
    ylim(8, -8)+
    theme_void()+
    theme(
      aspect.ratio = .5,
      legend.position = c(.13, .9),
      legend.text = element_text(color = "#ffffff"),
      legend.background = element_rect(
        fill = "#242424EE", colour = "#242424EE"
      )
    )

ggdraw()+
  draw_image(full_court_90_BW, scale = 1)+
  draw_plot(djoko_forehand_plot, x = 0, y = 0, scale = 1.15)
```

















































